#!/bin/bash
# This script runs a C file through the preprocessor and saves the result into another file.

# Set the C file name in the variable CFILE
CFILE="main.c"

# Run the C file through the preprocessor and save the output to a file called "c"
gcc -E "$CFILE" -o c
